### ISSUE TITLE
Master job (suggested feature)

### ISSUE THREAD

**Issue by ManuelCalavera** [zeagler/tangerine#34]
@zeagler I'm still thinking about this one, but wanted to get an idea out there.

The notion goes back to improving the experience for breaking out a large job into multiple small jobs.

The thought is basically:
> If I customer job truly consists of a multiple of smaller (sub) jobs, I don't necessarily want to see these sub jobs as scheduled unless the job:
> - is awaiting execution
> - is currently executing
> - has errored
> - is being edited
> 
> The idea further extends to making maintenance and managing (including editing) these type of jobs easier.

So, conceptually I decided to draw up a job schedule process in YAML (see below):
```
masterjob:
  -
    name: Cust1-MasterJob
    prefix: Cust1
    cron: "0 5 * * *"
    defaultEnvironment:
      - "JAVA_OPTIONS = -Xmx26g"
      - "APP_FILES = /app-files/config-files"
    defaultDataVolumes:
      - "/home/ubuntu/shared/folder1:/folder1"
      - "/home/ubuntu/shared/folder1/config-files/folder2:/home/app/folder2"
    defaultImage:
      - registry/user/image:1.1
  -
    jobs:
      -
        jobname: PreProcess
        jobtype: container
        command: kitchen.sh -file=/PreProcessJob.kjb -param:propertiesPath=/properties/Cust1.properties -logfile=/logs/Cust1/Cust1_PreProcess_$$date_$$time.log
      -
        jobname: Extract1
        jobtype: container
        jobtag: extract
        command: kitchen.sh -file=/PreProcessJob.kjb -param:propertiesPath=/properties/Cust1.properties -logfile=/logs/Cust1/Cust1_Extract1_$$date_$$time.log
        dependencies:
          - PreProcess
      -
        jobname: Extract2
        jobtype: container
        jobtag: extract
        command: kitchen.sh -file=/PreProcessJob.kjb -param:propertiesPath=/properties/Cust1.properties -logfile=/logs/Cust1/Cust1_Extract2_$$date_$$time.log
        dependencies:
          - PreProcess
      -
        jobname: Dimension1
        jobtype: container
        jobtag: dimension
        command: kitchen.sh -file=/Dimension_Job.kjb -param:artifactname=Dimension1 -param:propertiesPath=/properties/Cust1.properties -logfile=/logs/Cust1/Cust1_Dimension1_$$date_$$time.log
        dependencies:
          - "tag:extract"
      -
        jobname: Dimension2
        jobtype: container
        jobtag: dimension
        command: kitchen.sh -file=/Dimension_Job.kjb -param:artifactname=Dimension2 -param:propertiesPath=/properties/Cust1.properties -logfile=/logs/Cust1/Cust1_Dimension2_$$date_$$time.log
        dependencies:
          - "tag:extract"
      -
        jobname: Dimension3
        jobtype: container
        jobtag: dimension
        command: kitchen.sh -file=/Dimension_Job.kjb -param:artifactname=Dimension3 -param:propertiesPath=/properties/Cust1.properties -logfile=/logs/Cust1/Cust1_Dimension3_$$date_$$time.log
        dependencies:
          - Dimension1
      -
        jobname: Fact1
        jobtype: container
        jobtag: fact
        command: kitchen.sh -file=/Fact_Job.kjb -param:artifactname=Fact1  -param:propertiesPath=/properties/Cust1.properties -logfile=/logs/Cust1/Cust1_Fact1_$$date_$$time.log
        dependencies:
          - "tag:dimension"
```

Now, the above is a thought to start a conversation. It doesn't include several of the fields you've already added that are still very much useful. Instead, the above YAML sample includes only the bare minimum for this particular conversation.

In the above outline, there are a few thoughts and then some things implied:
- The "sub" jobs essentially rely on the schedule of the "master job". In other words, the sub jobs do not need their own cron.
- The "sub jobs" are actually created for each run. So when the "master job" starts it will create entries for all sub jobs (making them visible on the UI), and when the job completes (successfully) the "sub jobs" will be deleted.
- If an error occurs the outstanding sub jobs will still show as pending execution (dependencies), except for the errored job. Once no more executions can occur (because they execute in parallel), the main job will set itself to errored as well.
- Stopping the main job will also stop the sub jobs and then delete these sub jobs.
- Dimension dependencies in the above work in two different ways:
   - By job (just as you have today)
   - By tag. This prevents having to list out every dimension job for a fact run, but instead we can simply reference `tag:dimension` (making maintenance easier when we add/remove jobs)
- Certain job specifications can be inherited from the master job level (default)

What do you think? Not saying this (YAML in particular) is necessarily the solution, but this is more from making it easier.
